# -*- coding: utf-8 -*-

# Aptitudes

A_CHOICE = 'A_CHC'  # to use during character's creation to mark choosable apts

A_GENERAL = 'A_GEN'

A_WEAPON_SKILL = 'A_WS'
A_BALLISTIC_SKILL = 'A_BS'
A_STRENGTH = 'A_STR'
A_TOUGHNESS = 'A_T'
A_AGILITY = 'A_AG'
A_INTELLIGENCE = 'A_INT'
A_PERCEPTION = 'A_PER'
A_WILLPOWER = 'A_WP'
A_FELLOWSHIP = 'A_FEL'

A_OFFENCE = 'A_OFF'
A_DEFENCE = 'A_DEF'
A_FIELDCRAFT = 'A_FLD'
A_KNOWLEDGE = 'A_KNG'
A_SOCIAL = 'A_SOC'
A_PSYKER = 'A_PSY'
A_LEADERSHIP = 'A_LDR'
A_FINESSE = 'A_FIN'
A_TECH = 'A_TECH'

# Stats

ST_WEAPON_SKILL = 'ST_WS'
ST_BALLISTIC_SKILL = 'ST_BS'
ST_STRENGTH = 'ST_STR'
ST_TOUGHNESS = 'ST_T'
ST_AGILITY = 'ST_AG'
ST_INTELLIGENCE = 'ST_INT'
ST_PERCEPTION = 'ST_PER'
ST_WILLPOWER = 'ST_WP'
ST_FELLOWSHIP = 'ST_FEL'
ST_INFLUENCE = 'ST_IFL'

# Skills

SK_ACROBATICS = 'SK_ACR'
SK_ATHLETICS = 'SK_ATHL'
SK_AWARENESS = 'SK_AWR'
SK_CHARM = 'SK_CH'
SK_COMMAND = 'SK_CMD'
SK_COMMERCE = 'SK_CMR'
SK_COMMON_LORE = 'SK_CML'
SK_SCHOLASTIC_LORE = 'SK_SCL'
SK_FORBIDDEN_LORE = 'SK_FBL'
SK_DECEIVE = 'SK_DCV'
SK_DODGE = 'SK_DDG'
SK_INQUIRY = 'SK_INQ'
SK_INTERROGATION = 'SK_INTR'
SK_INTIMIDATE = 'SK_INTM'
SK_LINGUISTICS = 'SK_LNG'
SK_LOGIC = 'SK_LOG'
SK_MEDICAE = 'SK_MED'
SK_NAVIGATE = 'SK_NVG'
SK_OPERATE = 'SK_OPR'
SK_PARRY = 'SK_PAR'
SK_PSYNISCIENCE = 'SK_PSY'
SK_SCRUTINY = 'SK_SCR'
SK_SECURITY = 'SK_SEC'
SK_SLEIGHT_OF_HANDS = 'SK_SOH'
SK_STEALTH = 'SK_STL'
SK_TECH_USE = 'SK_TECH'
SK_TRADE = 'SK_TRD'

# Subtags

SUBTAGGED_SKILLS = [SK_COMMON_LORE, SK_SCHOLASTIC_LORE, SK_FORBIDDEN_LORE,
                    SK_LINGUISTICS, SK_NAVIGATE, SK_OPERATE,
                    SK_TRADE]

LORE_SORORITAS = 'LR_SOR'
LORE_ARBITES = 'LR_ARB'
LORE_ASTARTES = 'LR_AST'
LORE_AS_TEL = 'LR_ASTL'
LORE_MECHANICUS = 'LR_MECH'
LORE_ADMINISTRATUM = 'LR_ADM'
LORE_SECTOR = 'LR_SECT'
LORE_CHARTISTS = 'LR_CHRT'
LORE_TITANICUS = 'LR_TIT'
LORE_ECCLESIARCHY = 'LR_ECL'
LORE_IMPERIAL_CREED = 'LR_ICRD'
LORE_IMPERIAL_GUARD = 'LR_IGRD'
LORE_IMPERIAL_NAVY = 'LR_INVY'
LORE_IMPERIUM = 'LR_IMP'
LORE_NAVIGATORS = 'LR_NVG'
LORE_PLANETARY_DEFENCE = 'LR_PDF'
LORE_SCHOLA_PROGENIUM = 'LR_PROG'
LORE_TECH = 'LR_TECH'
LORE_UNDERWORLD = 'LR_UWLD'
LORE_WAR = 'LR_WAR'

LORE_ASTROMANCY = 'LR_ASMN'
LORE_BEASTS = 'LR_BST'
LORE_BUREAUCRACY = 'LR_BRC'
LORE_CHYMISTRY = 'LR_CHEM'
LORE_CRYPTOLOGY = 'LR_CRYPT'
LORE_HERALDRY = 'LR_HRLD'
LORE_IMPERIAL_WARRANTS = 'LR_IPWR'
LORE_JUDGEMENT = 'LR_JDG'
LORE_LEGEND = 'LR_LGND'
LORE_NUMEROLOGY = 'LR_NMR'
LORE_OCCULT = 'LR_OCLT'
LORE_PHILOSOPHY = 'LR_PHL'
LORE_TACTICA_IMPERIALIS = 'LR_TCIM'

LORE_ARCHAEOTECH = 'LR_ATECH'
LORE_CHAOS_SPACE_MARINES = 'LR_CSM'
LORE_CARTELS = 'LR_CTL'
LORE_DAEMONOLOGY = 'LR_DMNL'
LORE_HERESY = 'LR_HRS'
LORE_LONG_WAR = 'LR_LGW'
LORE_INQUISITION = 'LR_INQV'
LORE_MUTANTS = 'LR_MTNT'
LORE_OFFICIO_ASSASSINORUM = 'LR_ASS'
LORE_PIRATES = 'LR_PIR'
LORE_PSYKERS = 'LR_PSY'
LORE_WARP = 'LR_WRP'
LORE_XENOS = 'LR_XNS'

COMMON_LORES = [LORE_SORORITAS, LORE_ARBITES, LORE_ASTARTES, LORE_AS_TEL, LORE_MECHANICUS,
                LORE_ADMINISTRATUM, LORE_SECTOR, LORE_CHARTISTS, LORE_TITANICUS, LORE_ECCLESIARCHY,
                LORE_IMPERIAL_CREED, LORE_IMPERIAL_GUARD, LORE_IMPERIAL_NAVY, LORE_IMPERIUM, LORE_NAVIGATORS,
                LORE_PLANETARY_DEFENCE, LORE_SCHOLA_PROGENIUM, LORE_TECH, LORE_UNDERWORLD, LORE_WAR]

SCHOLASTIC_LORES = COMMON_LORES + [LORE_ASTROMANCY, LORE_BEASTS, LORE_BUREAUCRACY, LORE_CHYMISTRY,
                                   LORE_CRYPTOLOGY, LORE_HERALDRY, LORE_IMPERIAL_WARRANTS, LORE_JUDGEMENT,
                                   LORE_LEGEND, LORE_NUMEROLOGY, LORE_OCCULT, LORE_PHILOSOPHY,
                                   LORE_TACTICA_IMPERIALIS]

FORBIDDEN_LORES = SCHOLASTIC_LORES + [LORE_ARCHAEOTECH, LORE_CHAOS_SPACE_MARINES, LORE_CARTELS,
                                      LORE_DAEMONOLOGY, LORE_HERESY, LORE_LONG_WAR,
                                      LORE_INQUISITION, LORE_MUTANTS, LORE_OFFICIO_ASSASSINORUM,
                                      LORE_PIRATES, LORE_PSYKERS, LORE_WARP,
                                      LORE_XENOS]

LINGUISTICS_CHAPTER_RUNES = 'LN_CHR'
LINGUISTICS_CHAOS_MARKS = 'LN_CSMK'
LINGUISTICS_HIGH_GOTHIC = 'LN_HG'
LINGUISTICS_LOW_GOTHIC = 'LN_LG'
LINGUISTICS_IMPERIAL_CODES = 'LN_IC'
LINGUISTICS_GLOSSIA = 'LN_GL'
LINGUISTICS_ELDAR = 'LN_ELD'
LINGUISTICS_ORK = 'LN_ORK'
LINGUISTICS_NECRONTYR = 'LN_NECR'
LINGUISTICS_MERCENARY_CANT = 'LN_MRC'
LINGUISTICS_TECHNA_LINGUA = 'LN_TCL'
LINGUISTICS_TAU = 'LN_TAU'
LINGUISTICS_UNDERWORLD = 'LN_UWLD'
LINGUISTICS_XENOS_MARKINGS = 'LN_XNMK'

NAVIGATE_SURFACE = 'NV_SF'
NAVIGATE_STELLAR = 'NV_SL'
NAVIGATE_WARP = 'NV_WP'

OPERATE_SURFACE = 'OP_SF'
OPERATE_AERONAUTICA = 'OP_ARN'
OPERATE_VOIDSHIP = 'OP_VD'

TRADE_ARCHAEOLOGIST = 'TD_ARC'
TRADE_AGRI = 'TD_AGR'
TRADE_ARMOURER = 'TD_ARMR'
TRADE_ASTROGRAPHER = 'TD_ASGR'
TRADE_EXPLORATOR = 'TD_EXPL'
TRADE_LINGUIST = 'TD_LNG'
TRADE_MORTICATOR = 'TD_MRT'
TRADE_PERFORMANCER = 'TD_PRF'
TRADE_PROSPECTOR = 'TD_PRS'
TRADE_SCRIMSHAVER = 'TD_SCR'
TRADE_SCULPTOR = 'TD_SCLP'
TRADE_SHIPWRIGHT = 'TD_SPWR'
TRADE_SOOTHSAYER = 'TD_STSR'
TRADE_TECHNOMAT = 'TD_TCMT'
TRADE_VOIDFARER = 'TD_VDFR'

# Roles

ROLE_ASSASSIN = 'R_ASS'
ROLE_CHIRURGEON = 'R_CHRG'
ROLE_DESPERADO = 'R_DSP'
ROLE_HIEROPHANT = 'R_HRPT'
ROLE_MYSTIC = 'R_MST'
ROLE_SAGE = 'R_SAGE'
ROLE_SEEKER = 'R_SKR'
ROLE_WARRIOR = 'R_WR'

ROLE_CRUSADER = 'R_CRD'
ROLE_ACE = 'R_ACE'
ROLE_FANATIC = 'R_FNT'
ROLE_PENITENT = 'R_PNT'

# Backgrounds

BACKGROUND_ADMINISTRATUM = 'BG_ADMR'
BACKGROUND_ASTRA_TELEPATHICA = 'BG_ATPT'
BACKGROUND_ARBITES = 'BG_ARB'
BACKGROUND_MECHANICUS = 'BG_ADMC'
BACKGROUND_MINISTORUM = 'BG_ADMS'
BACKGROUND_ASTRA_MILITARUM = 'BG_ASML'
BACKGROUND_OUTCAST = 'BG_OUT'

BACKGROUND_HERETEK = 'BG_HRT'
BACKGROUND_NAVY = 'BG_NAVY'
BACKGROUND_RT_FLEET = 'BG_RTFL'
BACKGROUND_EXCORCISED = 'BG_XRC'
BACKGROUND_SORORITAS = 'BG_ADSR'
BACKGROUND_MUTANT = 'BG_MTN'

# Homeworlds

HOMEWORLD_FERAL = 'HW_FRL'
HOMEWORLD_FORGE = 'HW_FRG'
HOMEWORLD_HIGHBORN = 'HW_HGB'
HOMEWORLD_HIVE = 'HW_HIVE'
HOMEWORLD_SHRINE = 'HW_SHR'
HOMEWORLD_VOIDBORN = 'HW_VDB'

HOMEWORLD_DEATH = 'HW_DTH'
HOMEWORLD_GARDEN = 'HW_GDN'
HOMEWORLD_STATION = 'HW_STN'
HOMEWORLD_DAEMON = 'HW_DMN'
HOMEWORLD_PENAL = 'HW_PEN'
HOMEWORLD_QUARANTINE = 'HW_QRTN'
HOMEWORLD_AGRI = 'HW_AGRI'
HOMEWORLD_FEUDAL = 'HW_FDL'
HOMEWORLD_FRONTIER = 'HW_FRTR'
